services:
  postgres:
    image: postgres:16-alpine
    container_name: trainup-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trainup
    volumes:
      - trainup-data:/var/lib/postgresql/data

volumes:
  trainup-data:
